### ISSUE TITLE
Missing license ?

### ISSUE THREAD

**Issue by dkm** [msyksphinz-self/riscv-isadoc#1]
Hi,

I was looking for some riscv ISA documentation that can be easily used in script (ultimate goal is to have online documentation in compiler-explorer, see  https://github.com/mattgodbolt/compiler-explorer/pull/1291 ). The LaTeX released by the RV foundation is hardly a good candidate, but your rst files definitely are !
Before reusing your work, maybe you could make the license more explicit ? I guess that you've based your work on the original specification which is released under CC Attribution 4.0 International but I'm not even sure of that as it seems the text is not the same.

**Comment by msyksphinz-self** [comment]
Sorry for my late response. Yes you can use same as original specification, CC 4.0.
I added LICENSE file. Thank you for your proposal!

**Comment by dkm** [comment]
Thanks !
